PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE USERS(ID INT PRIMARY KEY     NOT NULL, NAME           TEXT    NOT NULL, AGE            INT     NOT NULL);
INSERT INTO USERS VALUES(1,'Alice',30);
INSERT INTO USERS VALUES(2,'Bob',25);
INSERT INTO USERS VALUES(3,'Charlie',35);
COMMIT;
